source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts

# Server
exclude: ['+compile.rb', '+status.rb', 'start.rb', 'style.yml', 'src', 'cleanup.rb', 'compass-dev.rb', 'compass-production.rb']

# Permalinks
permalink:   pretty